// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3D3yuUenU1yDpWdY8NRgryCwxS-VDBZI',
    appId: '1:8649007811:web:4df06a257eec1ebcb5f876',
    messagingSenderId: '8649007811',
    projectId: 'driveuploading-406406',
    authDomain: 'driveuploading-406406.firebaseapp.com',
    storageBucket: 'driveuploading-406406.appspot.com',
    measurementId: 'G-FH6FYEWMQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY5a-_7AD0MQ_ftaFb10-XvvP4dMBpeYU',
    appId: '1:8649007811:android:302eef2b343da981b5f876',
    messagingSenderId: '8649007811',
    projectId: 'driveuploading-406406',
    storageBucket: 'driveuploading-406406.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpJ9QDNqHH8qTlzUYG1Hm-nGKzFumLroY',
    appId: '1:8649007811:ios:709fee8e25df42f6b5f876',
    messagingSenderId: '8649007811',
    projectId: 'driveuploading-406406',
    storageBucket: 'driveuploading-406406.appspot.com',
    iosBundleId: 'com.example.gdrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpJ9QDNqHH8qTlzUYG1Hm-nGKzFumLroY',
    appId: '1:8649007811:ios:9a6b71176a243bf5b5f876',
    messagingSenderId: '8649007811',
    projectId: 'driveuploading-406406',
    storageBucket: 'driveuploading-406406.appspot.com',
    iosBundleId: 'com.example.gdrive.RunnerTests',
  );
}
